name: current_app_detector
description: A Flutter plugin to detect the current foreground app and navigate to home screen. Provides getCurrentApp() and goHome() methods for Android.
version: 1.0.0
homepage: https://github.com/Shiva-04z/current_app_detector
repository: https://github.com/Shiva-04z/current_app_detector

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.current_app_detector
        pluginClass: CurrentAppDetectorPlugin